#version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskmanagementappdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-web
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://flaskuser:flaskpassword@mysql:3306/flaskmanagementappdb
      SECRET_KEY: mydevkey
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: AdminPassword123!
    command: 
      ["bash", "./wait-for-it.sh", "mysql:3306", "--strict", "--timeout=100", "--", "flask", "run", "--host=0.0.0.0"]



volumes:
  mysql_data:
