"""Add sprint_id to Task

Revision ID: 9ddb43b4abb7
Revises: 1479ed996c4e
Create Date: 2024-12-17 12:42:26.226048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddb43b4abb7'
down_revision = '1479ed996c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sprints', ['sprint_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sprint_id')

    # ### end Alembic commands ###
